# Generated by Django 4.2.4 on 2023-08-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='allergic_customers', to='main.ingredient'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='preferred_customers', to='main.ingredient'),
        ),
    ]
