# Generated by Django 4.2.4 on 2023-08-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish_img_dish_price_alter_menu_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuofRestaurant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.menu',),
        ),
    ]
