# Generated by Django 4.2.4 on 2023-08-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menuofrestaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantofMan',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.restaurant',),
        ),
    ]
