# Generated by Django 4.2.4 on 2023-08-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dish_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishofMan',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dish',),
        ),
    ]
