# Generated by Django 4.2.4 on 2023-08-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dishofman'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='more_info',
            field=models.JSONField(default={}),
        ),
    ]
