# Generated by Django 4.2.4 on 2023-08-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ingredient_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='more_info',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
